### ISSUE TITLE
tryCatch didn't gracefully handle an antiword error

### ISSUE THREAD

**Issue by soshsquatch** [ropensci/antiword#1]
Thought others may run across a similar issue. I'm processing a large number of MS word documents, and one of them is apparently corrupted (it's attached). Antiword produced the following error: 

`System call to 'antiword' failed (1): Read long 0x7a74 not possible`

 I tried using tryCatch(antiword(file), finally=as.character(NA)), but tryCatch didn't save me. I didn't understand how to get around this. Tried signalCondition() clumsily but with no luck.

So, inside the 'antiword' function there is a 'stop' command. All I really need is a warning, so to hack my way around this, I wrote this myantiword function:

 is_windows <- function(){
    identical(.Platform$OS.type, "windows")
  }

  myantiword <- function (file = NULL, format = FALSE)
  {
    args <- if (length(file)) {
      if (grepl("^https?://", file)) {
        tmp <- tempfile(fileext = ".doc")
        utils::download.file(file, tmp, mode = "wb")
        file <- tmp
      }
      file <- normalizePath(file, mustWork = TRUE)
      c(ifelse(isTRUE(format), "-f", "-t"), ifelse(is_windows(),
                                                   shQuote(file), file))
    }
    wd <- getwd()
    on.exit(setwd(wd))
    bindir <- system.file("bin", package = "antiword")
    setwd(bindir)
    postfix <- if (is_windows())
      .Machine$sizeof.pointer * 8
    path <- file.path(bindir, paste0("antiword", postfix))
    out <- sys::exec_internal(path, args, error = FALSE)
  
    if (out$status == 0) {
      if (length(out$stderr))
        cat(rawToChar(out$stderr), file = stderr())
      return(rawToChar(out$stdout))
    } else {
      warning(sprintf("System call to 'antiword' failed (%d): %s",
                      out$status, rawToChar(out$stderr)))
      return(as.character(NA))
    }

  }

[BILL_ANALYSIS_TBL_20913.doc.zip](https://github.com/ropensci/antiword/files/1522914/BILL_ANALYSIS_TBL_20913.doc.zip)

**Comment by ekoraytascilar** [comment]
I ran into a similar issue with the` readtext::readtext` function throwing a ` System call to 'antiword' failed (1): The Big Block Depot is damaged` error probably due to a corrupt file, i hope i was as sophisticated an r user as to attempt to overcome it.
Cluld you please alert me as soon as you find a workaround? @predict-r 
I suppose in my case the question is how can i direct the system call to "myantiword" instead of antiword so that i can get away with a warning.

**Comment by ekoraytascilar** [comment]
In my case i used the following code to edit the antiword function and change the error to a warning so that it did not interrupt my batch read.
`fixInNamespace(antiword, pos="package:antiword")`

**Comment by jeroen** [comment]
Is this still an issue? Which operating system are you using? For me this works:

```r
res <- try(antiword("~/Downloads/BILL_ANALYSIS_TBL_20913.doc"), silent = T)
```

**Comment by soshsquatch** [comment]
No, this isn't an issue...I forgot the details so will close it.
